### ISSUE TITLE
Android 7 MaterialIndicator broken

### ISSUE THREAD

**Issue by yellow-pomelo** [n4kz/react-native-indicators#5]
Hi, 
   while using the library on Android 7, the MaterialIndicator behaves like this:
![spinner-android](https://user-images.githubusercontent.com/26478422/35789731-31fde23a-0a92-11e8-8e61-ed3e3b98c73a.gif)

  it happens both on a simulator and a real device. All is fine on older Android versions and IOS.

react-native: v0.51.0
react-native-indicators: v0.11.0

**Comment by n4kz** [comment]
Thanks for reporting! Looks like some animations with `borderRadius` were broken in recent RN versions. I've found similar reports in facebook/react-native#17224 and facebook/react-native#17400. I can suggest using RN `0.50.4` or another indicator if downgrading is not an option until this issue is resolved in RN.
